// const countryList = {
//   AFN: "AF",
//   EUR: "AX ",
//   ALL: "AL ",
//   DZD: "DZ ",
//   USD: "AS ",
//   EUR: "AD ",
//   AOA: "AO ",
//   XCD: "AI ",
//   ARS: "AR ",
//   AMD: "AM ",
//   AWG: "AW ",
//   AUD: "AU",
//   EUR: "AT ",
//   AZN: "AZ",
//   BSD: "BS",
//   BHD: "BH ",
//   BDT: "BD ",
//   BBD: "BB ",
//   EUR: "BE",
//   CAD: "CA ",
//   AUD: "HM",
//   HNL: "HN",
//   HKD: "HK",
//   HUF: "HU ",
//   ISK: "IS",
//   INR: "IN",
//   IDR: "ID ",
//   IRR: "IR",
//   IQD: "IQ",
//   EUR: "IE",
//   GBP: "IM ",
//   ILS: "IL ",
//   EUR: "IT ",
//   JMD: "JM",
//   JPY: "JP ",
//   GBP: "JE ",
//   JOD: "JO",
//   KZT: "KZ ",
//   KES: "KE ",
//   AUD: "KI ",
//   KPW: "KP",
//   KRW: "KR ",
//   KWD: "KW ",
//   KGS: "KG ",
// };

const countryList = {
  INR: "IN",
  BDT: "BD",
  BYN: "BY",
  EUR: "BE",
  BBD: "BB",
  AFN: "AF",
  ALL: "AL",
  DZD: "DZ",
  USD: "AS",
  ARS: "AR",
  USD: "AQ",
  CAD: "CA",
  CNY: "CN",
  EGP: "EG",
  EUR: "FI",
  HKD: "HK",
  EUR: "IE",
  ZWL: "ZW",
  YER: "YE",
  ZMW: "ZM",
  VND: "VN",
  UYU: "UY",
  UZS: "UZ",
  USD: "US",
  AED: "AE",
  UAH: "UA",
  LKR: "LK",
  KRW: "KR",
  ZAR: "ZA",
  PKR: "PK",
  JPY: "JP",
};
